spring.application.name=sgpp
# Permite a Flyway ejecutar la migración incluso si la versión del 
# servidor no coincide exactamente con las versiones soportadas.
spring.flyway.validate-on-migrate=false
#puerto del servidor
server.port=8080
#confirmación de la base de datos postgresql
spring.datasource.url=jdbc:postgresql://localhost:5432/sgpp_db
spring.datasource.username=sgpp_user
spring.datasource.password=Bpcd1234
spring.datasource.driver-class-name=org.postgresql.Driver
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration, org.springframework.boot.actuate.autoconfigure.security.servlet.ManagementWebSecurityAutoConfiguration

#formatea las consultas sql en la consola
spring.jpa.properties.hibernate.format_sql=true
#desabilita la creación automática de tablas
spring.jpa.hibernate.ddl-auto=none
#las migraciones de Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migrations

#seguridad con jwt
app.security.jwt.secret=7d424b966f1e8e3a2c5a0f8b1c4e6a0d2f3c7b8e1a9d0f6e3c1b0a5d2e7f4c6b
app.security.jwt.expiration=3600000 #1 hora en milisegundos
# Deshabilita la validación de la versión de la base de datos de forma explícita en Flyway.
flyway.skip-version-check=true