#==============================================================================
# INFORMACIÓN DE LA APLICACIÓN
#==============================================================================
spring.application.name=sgpp
server.port=8080
server.servlet.context-path=/sgpp 

#==============================================================================
# CONFIGURACIÓN DE LA BASE DE DATOS - POSTGRESQL
#==============================================================================
spring.datasource.url=jdbc:postgresql://localhost:5432/sgpp_db
spring.datasource.username=postgres
spring.datasource.password=tu_password_aqui
spring.datasource.driver-class-name=org.postgresql.Driver

#==============================================================================
# CONFIGURACIÓN DE JPA / HIBERNATE
#==============================================================================